### ISSUE TITLE
Update is not supported in azapi_resource. Code base is broken

### ISSUE THREAD

**Issue by bryansan-msft** [Azure/terraform-azurerm-avm-res-storage-storageaccount#85] opened 2024-05-06 12:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.7.5

### Module Version

code base in this repository

### AzureRM Provider Version

for azapi 1.12.0 and 1.13.1

### Affected Resource(s)/Data Source(s)

azapi_resource

### Terraform Configuration Files

```hcl
As I mentioned in the title. Code base is broken. Any of your examples cant run
```

### tfvars variables values

```hcl
Nothing at all
```

### Debug Output/Panic Output

```shell
PS C:\Workspace\terraform-azurerm-avm-res-storage-storageaccount\examples\default> terraform apply -auto-approve
╷
│ Error: Unsupported argument
│
│   on ..\..\main.containers.tf line 21, in resource "azapi_resource" "containers":
│   21:       update = timeouts.value.update
│
│ An argument named "update" is not expected here.
```

### Expected Behaviour

Terraform should just run

### Actual Behaviour

Error as update parameter is not supported in this resources

### Steps to Reproduce

just terraform apply

### Important Factoids

Nothing at all

### References

Nothing at all

**Comment by chinthakaru** [comment] 2024-05-09 08:23
@bryansan-msft thanks for reaching out. there was a change on Azapi_resource v1.13. Let me get back to you asap.

**Comment by kewalaka** [comment] 2024-05-12 00:42
duplicate of #78

**Comment by chinthakaru** [comment] 2024-05-24 13:07
Sorry for the delayed update; we have temporarily removed the `update` argument until it becomes available in a future release.

**Comment by kewalaka** [comment] 2024-05-24 18:01
@chinthakaru are you planning to make a release as well?  I've been working off my forked dev version for a while, be good to get back to upstream.

**Comment by chinthakaru** [comment] 2024-06-03 14:23
@bryansan-msft Removed the Update Argument and code is working again.

**Closed** 2024-06-03 14:31 UTC
Labels: Status: Fixed :white_check_mark:
